spring:
  datasource:
    password: mi3909
    url: jdbc:mysql://localhost:3306/demo
    username: gmiskos
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
